version: '3.3'
services:
    memos:
        container_name: memos
        volumes:
            - '~/.memos/:/var/opt/memos'
        image: 'neosmemo/memos:latest'
        networks:
          - public_net

networks:
  public_net:
    external: true
